"""
HTTP Client (Single Responsibility Principle).
Responsible ONLY for making the Purchase Order API call.
No business logic lives here.
"""
import logging
import httpx
from datetime import date
from typing import Dict, Any
from cronjobs.jobs.daily_purchase_suggestion.config import PurchaseSuggestionConfig

logger = logging.getLogger(__name__)


class PurchaseApiClient:
    """
    Thin async HTTP wrapper around the ERP purchase-service endpoint.
    Auth token, base URL, and company/user IDs all come from config (→ .env).
    """

    def __init__(self, config: PurchaseSuggestionConfig):
        self._config = config

    def _build_headers(self) -> Dict[str, str]:
        return {
            "Accept": "application/json",
            "Authorization": f"Bearer {self._config.ERP_AUTH_TOKEN}",
            "Content-Type": "application/json; charset=UTF-8",
            "x-company-id": self._config.ERP_COMPANY_ID,
            "x-company-ids": f"[{self._config.ERP_COMPANY_ID}]",
        }

    def _build_payload(self, product: Dict[str, Any], suggested_qty: float) -> Dict[str, Any]:
        """
        Constructs the PO creation payload.
        status_id = PO_STATUS_ID from .env (defaults to 34 = "pending").
        """
        today = date.today().isoformat()
        return {
            "purchase_type_id": self._config.PO_PURCHASE_TYPE_ID,
            "company_id": int(self._config.ERP_COMPANY_ID),
            "status_id": self._config.PO_STATUS_ID,          # ← "pending"
            "document_date": today,
            "supplier_entity_id": product["supplier_entity_id"],
            "buyer_id": int(self._config.ERP_COMPANY_ID),
            "user_id": int(self._config.ERP_USER_ID),
            "poc_id": None,
            "external_reference_id": "",
            "inco_terms_id": None,
            "estimated_departure_time": None,
            "estimated_arrival_time": today,
            "actual_arrival_date": today,
            "gross_amount": 0,
            "net_amount": 0,
            "order_remarks": "Auto-generated by Daily Purchase Suggestion Cron",
            "party_reference_number": "",
            "items": [
                {
                    "product_id": str(product["product_id"]),
                    "item_name": product["item_name"],
                    "description": "",
                    "brand": "",
                    "item_group": "",
                    "mode_of_packaging": "",
                    "quantity": suggested_qty,
                    "quality": "",
                    "rate": float(product.get("rate") or 0),
                    "hsn_code": "",
                    "uom_id": product.get("uom_id") or 13,
                    "no_of_packages": 0,
                    "net_weight_of_package": 0,
                    "gross_weight_of_package": 0,
                    "net_weight_of_item": 0,
                    "gross_weight_of_item": 0,
                    "gsm": None,
                    "size_1": None,
                    "size_2": None,
                    "size_cm": None,
                    "size_inch": None,
                    "size_type": "",
                    "number_of_sheets": None,
                    "ream_weight": None,
                    "tare_weight": None,
                    "fsc_type": "",
                    "variant_key": "",
                    "remarks": "",
                    "due_date": None,
                    "price": float(product.get("rate") or 0),
                    "total_weight": 0,
                    "per_bundles": 0,
                    "per_bundles_unit": "",
                }
            ],
            "linked_sales_order": "",
            "payment_terms": {
                "default_payment_term": "",
                "credit_limit": 0,
                "credit_period": 0,
                "discount_allowed": False,
                "tds_applicable": False,
                "tds_rate": 0,
                "tcs_applicable": False,
                "delivery_terms_days": 0,
                "price_list_id": None,
            },
            "insurance": {
                "insurer_name": "",
                "insurance_terms": "",
                "policy_number": "",
                "policy_exp_date": today,
                "insurance_amount": 0,
            },
            "tax_details": [
                {
                    "tax_type_id": tax_id,
                    "transaction_type_id": self._config.PO_TRANSACTION_TYPE_ID,
                }
                for tax_id in self._config.PO_TAX_TYPE_IDS
            ],
            "bill_to_address_id": self._config.PO_BILL_TO_ADDRESS_ID,
            "ship_to_address": self._config.PO_SHIP_TO_ADDRESS_ID,
            "terms_ids": [],
        }

    async def create_purchase_order(
        self, product: Dict[str, Any], suggested_qty: float
    ) -> Dict[str, Any]:
        """
        Calls POST /V1/purchase-service with status = pending.
        Returns the parsed JSON response.
        """
        url = self._config.purchase_api_url
        headers = self._build_headers()
        payload = self._build_payload(product, suggested_qty)

        logger.info(
            f"[PurchaseApiClient] Creating PO for product_id={product['product_id']} "
            f"qty={suggested_qty} → POST {url}"
        )

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(url, json=payload, headers=headers)

        if response.status_code in (200, 201):
            data = response.json()
            po_number = data.get("data", {}).get("po_number", "N/A")
            logger.info(
                f"[PurchaseApiClient] PO created successfully: {po_number} "
                f"for product_id={product['product_id']}"
            )
            return data
        else:
            logger.error(
                f"[PurchaseApiClient] API call failed for product_id={product['product_id']} "
                f"status={response.status_code} body={response.text}"
            )
            response.raise_for_status()
